"""Keywords

Revision ID: 4c210c14c463
Revises: f0b33beec782
Create Date: 2024-11-18 18:40:51.857209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c210c14c463'
down_revision: Union[str, None] = 'f0b33beec782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_articles', sa.Column('keywords', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processed_articles', 'keywords')
    # ### end Alembic commands ###
