"""Add indexes to Article table

Revision ID: 64e61861ccdb
Revises: 05caa4fafdf0
Create Date: 2024-09-22 19:19:50.665040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '64e61861ccdb'
down_revision: Union[str, None] = '05caa4fafdf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_articles_newspaper_id', 'articles', ['newspaper_id'], unique=False)
    op.create_index('ix_articles_published_at', 'articles', ['published_at'], unique=False)
    op.create_index('ix_articles_section_id', 'articles', ['section_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_articles_section_id', table_name='articles')
    op.drop_index('ix_articles_published_at', table_name='articles')
    op.drop_index('ix_articles_newspaper_id', table_name='articles')
    # ### end Alembic commands ###
